version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888" # Expose app on port 8081
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    ports:
      - "3307:3306" # Expose MySQL on port 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dating_apps_local
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - "6380:6379" # Expose Redis on port 6380
    command: [ "redis-server", "--port", "6379" ]

volumes:
  db_data:
